services:
  apache-php:
    image: php:8.2-apache
    container_name: xampp-apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./.env:/root/.env:ro
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
      && sed -ri -e 's!/var/www/!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
      && docker-php-ext-install mysqli pdo pdo_mysql
      && sleep 3
      && chmod +x /var/www/html/init_admin.sh
      && /var/www/html/init_admin.sh
      && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: xampp-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./www/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./.env:/root/.env:ro
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: xampp-phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
